Improving logger
enso-org/rust-lib pull request #23
Opened 2020-11-25 07:27 UTC by wdanilo

### Pull Request Description
This PR implements better console logging utilities. Chrome doesn't allow to neither define warning and error `console.group`s, nor [allow filtering them, which sucks, and which was reported 6 years ago](https://bugs.chromium.org/p/chromium/issues/detail?id=363796&q=filter%20group%20console&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified). This new solution just uses our coloring instead of chrome coloring and allows filtering the errors by writing `[W]` in filter field instead of choosing the drop down menu.

![image](https://user-images.githubusercontent.com/1623053/100195705-05435d00-2ef8-11eb-9a97-f899b0a8d049.png)

### Important Note
- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guide.
- [x] All code has been tested where possible.

2020-11-25 09:52 UTC, farmaazon requested changes
1. I don't know how printing [W] instead of warning level will help avoiding bug you pasted. The report does not mention warnings nor errors at all, or filtering by them. Therefore I don't understand why we resign from simplicity and intuitiveness - anyone looking through logs cannot filter warnings/errors by level. The reason should be clearly documented, and I think the logger should at least print a warning on program start, that usual levels filtering does not work.

But I'm still not sure if I like the tradeoff - ability to group warnings, but at cost of weirdness to the debugging person.

2020-11-25 09:52 UTC, farmaazon commented on src/logger/src/lib.rs
> +    /// verbosity.
What is logged with warning level? The group "header" or all logs inside groups?

2020-11-25 09:52 UTC, farmaazon commented on src/logger/src/lib.rs
> +
Please make the same for error.

2020-11-25 13:41 UTC, farmaazon approved these changes

2020-11-27 08:54 UTC, farmaazon approved these changes

2020-11-27 08:54 UTC, farmaazon commented on src/logger/Cargo.toml
> +js-sys = { version = "0.3.28" }
Align please.

2020-11-27 08:54 UTC, farmaazon commented on src/logger/src/entry.rs
> +    // FIXME: Unused collapsed
FIXME left without issue number.

2020-11-27 08:54 UTC, farmaazon commented on src/logger/src/entry.rs
> +        let content    = Content::GroupBegin(message.get());
Alignment.

2020-11-27 08:54 UTC, farmaazon commented on src/logger/src/entry.rs
> +        let content    = Content::GroupEnd;
Alignment.

2020-11-27 08:54 UTC, farmaazon commented on src/logger/src/lib.rs
> +use crate::sink::Sink;
`use crate::` should go first.

2020-11-27 08:54 UTC, farmaazon commented on src/logger/src/lib.rs
>      }
Isn't that just a clone?
If not explain in docs why because it is not obvious for me.

2020-11-27 08:54 UTC, farmaazon commented on src/logger/src/lib.rs
> +    where S:LevelSink<Level>, Level:From<L> {
```suggestion
where S:LevelSink<Level>, Level:From<L> {
```

2020-11-27 08:54 UTC, farmaazon commented on src/logger/src/macros.rs
> +            ($d($d ts:tt)*) => {
Please add a little comment (before macro) to explain the $d magic thing you described me on PM.

2020-11-27 12:33 UTC, wdanilo commented on src/logger/Cargo.toml
> +js-sys = { version = "0.3.28" }
As agreed via phone, we will autoforat cargo.tol now

2020-11-27 12:33 UTC, wdanilo commented on src/logger/src/entry.rs
> +    // FIXME: Unused collapsed
Ill fix it in a moment

2020-11-27 12:34 UTC, wdanilo commented on src/logger/src/lib.rs
>      }
Nope, as agreed via phone, this is visible when looking at the signature

2020-11-27 12:54 UTC, farmaazon commented on src/logger/src/lib.rs
> +use prelude::*;
prelude-like imports should go before crate... or it should be reexported here.

2020-11-27 12:54 UTC, farmaazon commented on src/logger/src/sink.rs
> +    fn submit(&mut self, input:Input) -> Self::Output;
From the docs and signature I don't know why I need to provide some Output of Sink, as sink by definition is something what receives events, not producing any output.

2020-11-27 12:54 UTC, farmaazon commented on src/logger/src/sink.rs
> +/// `Pipe<Sink1,Sink2,Sink3,Sink4>`.
Again, "connected sinks in a linear fashion" sounds strangely, as sinks rather receive information, than produce any. Somewhere I read "sink" as being a synonym of "listener".

In spring something like that is called Processor https://docs.spring.io/spring-cloud-stream/docs/Brooklyn.RELEASE/reference/html/_programming_model.html#__literal_source_literal_literal_sink_literal_and_literal_processor_literal

2020-11-27 14:53 UTC, MichaelMauderer reviewed
Code looks fine to me, but it might be good to add more documentation and examples.

Also, there are no tests that check logging, filtering etc.

2020-11-27 14:53 UTC, MichaelMauderer commented on src/logger/src/entry.rs
> +#[allow(missing_docs)]
It might be good to have docs here. It is, for example, not obvious what the `path` in this struct is referring to.

2020-11-27 14:53 UTC, MichaelMauderer commented on src/logger/src/entry.rs
> +//! Logger entry. Entry can contain message, grouping, time information, etc.
This doc should probably have additional information about the grouping and usage examples. Can groups be hierarchical?

2020-11-27 14:53 UTC, MichaelMauderer commented on src/logger/src/entry/level.rs
> +/// Utility for defining verbosity levels. See an example usage below.
This should have docs on usage. What is the input and what is the output?
The example does not show that.

2020-11-27 14:53 UTC, MichaelMauderer commented on src/logger/src/entry/level.rs
> +/// Utility for defining verbosity level groups. See an example usage below.
Should also have docs on usage in and output

2020-11-27 14:53 UTC, MichaelMauderer commented on src/logger/src/lib.rs
> +/// The main logger implementation.
If this is the main implementation, this should probably have the main documentation explaining all there is to know about the logger. With some usage examples, too.

2020-11-27 14:53 UTC, MichaelMauderer commented on src/logger/src/lib.rs
> +/// below to learn more.
Explained with examples would be useful here. From briefly reading this without using macro expansion  it is non-obvious how the filtering rules are built: why is `Debug` not part of `level::from::Debug`?

2020-11-27 14:53 UTC, MichaelMauderer commented on src/logger/src/macros.rs
> +//! Utilities for easy logger usage. Defines such macros as `debug!` or `warning!`.
Would be good to have some usage examples here.

2020-11-27 14:53 UTC, MichaelMauderer commented on src/logger/src/processor.rs
> +//! Logger processor implementation.
Might be useful to add some explanation to the docs about what these are used for why they are used. Maybe an example of a processor.

2020-11-27 14:53 UTC, MichaelMauderer commented on src/logger/src/processor.rs
> +/// or `Pipe<P1,P2,P3,P4>`.
Would be cool to see this used in a doc comment.

2020-11-27 14:53 UTC, MichaelMauderer commented on src/logger/src/processor/formatter/js_console.rs
> +    default fn format(path:&str, entry:&entry::Content) -> Option<Self::Output> {
Whitespace.

2020-11-30 04:59 UTC, wdanilo commented on src/logger/src/lib.rs
> +/// below to learn more.
I would not paste here example, as the generated code is pretty complex and everyone can expand it in intellij, however, I copletely agree that the syntax in this macro was isleading, so I changed it to:

```rust
define_compile_time_filtering_rules! {
    for level::from::Debug   remove Trace;
    for level::from::Info    remove Trace,Debug;
    for level::from::Warning remove Trace,Debug,Info;
    for level::from::Error   remove Trace,Debug,Info,Warning;
}
```

2020-11-30 05:00 UTC, wdanilo commented on src/logger/src/processor/formatter/js_console.rs
> +    default fn format(path:&str, entry:&entry::Content) -> Option<Self::Output> {
Wait, where? :D

2020-11-30 07:13 UTC, merged